Removed Bluejay in favor of a CoreBluetooth implementation
LedgerHQ/hw-transport-ios-ble pull request #5
Opened 2022-08-13 12:35 UTC by DantePuglisi

Created `BleModule` which will take the place of Bluejay for all Bluetooth interactions.

It implements a Queue of `Operations` which are run sequentially.

It takes the same time as Bluejay to perform actions like install an app to the device.

`BleTransportProtocol` remains the same (except than now we made `PeripheralIdentifier` public so `DeviceIdentifier` has been removed) so no major changes should be needed.

2022-09-10 05:02 UTC, harrisonf-ledger requested changes
Looks like there is a circular reference somewhere with Disconnect:
<img width="1226" alt="Screen Shot 2022-09-10 at 10 02 47 AM" src="https://user-images.githubusercontent.com/101927640/189469888-dbec5211-9cb9-473a-93a6-60ad907a993b.png">

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
>          }
This could be a bit more readable and testable if most of this was broken out into small functions. Some of them could be computed properties on their respective objects

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
> +                if connectedPeripheralTuple.canWriteWithoutResponse == nil {
Is there a meaningful difference between `canWriteWithoutResponse` being false vs nil?

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
> +            self.bleModule.connect(peripheralIdentifier: peripheral, timeout: .seconds(5)) { [weak self ] result in
Extra space here
```suggestion
            self.bleModule.connect(peripheralIdentifier: peripheral, timeout: .seconds(5)) { [weak self] result in
```

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
>                  switch result {
Add a strong self check here to avoid all the optional selfs below

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
> +        guard let peripheralService = configuration.services.first(where: { configService in peripheralsServicesTuple.first(where: { $0.peripheral.uuid == connectedPeripheral.uuid })?.serviceUUID ==
This could be made into a function and tested

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
> +        let apduToSend = APDU(data: [0x08,0x00,0x00,0x00,0x00])
This APDU should be a constant somewhere, such as a static property on APDU itself

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/BleTransport.swift
>              print("Error infering MTU: \(error.localizedDescription)")
typo:
```suggestion
            print("Error inferring MTU: \(error.localizedDescription)")
```

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +    private var delegate: BleModuleDelegate!
Should be `weak var` I believe

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +    func start(delegate: BleModuleDelegate) {
Could this just be an init? Then we can avoid the force unwrapping of `self.delegate` and `self.cbCentralManager`

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +            if let peripheral = connectedPeripheral {
Use guard let here to reduce nesting

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +            if let peripheral = connectedPeripheral {
Use guard let here to reduce nesting

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +        delegate.bluetoothAvailable(central.state == .poweredOn)
Is this enough feedback to allow the client to handle various permission states for both iOS and MacOS?

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Characteristic/DiscoverCharacteristic.swift
> +    deinit {
Remove this if it's not being used

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Characteristic/DiscoverCharacteristic.swift
> +    var peripheral: CBPeripheral
This can be a `let`

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Disconnect/Disconnect.swift
> +    deinit {
Remove this if it's not being used

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Listen/Listen.swift
> +    deinit {
Remove this if it's not being used

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Listen/Listen.swift
> +    var value: Bool
These can all be `let`

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Peripheral/Peripheral.swift
> +    private(set) var cbPeripheral: CBPeripheral!
This could be 
```suggestion
   let cbPeripheral: CBPeripheral
```

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Peripheral/Peripheral.swift
> +    /*public func peripheral(_ peripheral: CBPeripheral, didWriteValueFor characteristic: CBCharacteristic, error: Error?) {
We should probably remove this if we don't need it

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Peripheral/Peripheral.swift
> +extension Peripheral: CBPeripheralDelegate {
Remove references to Bluejay in the doc comments below here

2022-09-10 05:02 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Write/Write.swift
> +    var writeType: CBCharacteristicWriteType
These can all be `let`

2022-09-15 12:41 UTC, DantePuglisi commented on Sources/BleTransport/BleTransport.swift
> +                if connectedPeripheralTuple.canWriteWithoutResponse == nil {
Yes, `canWriteWithoutResponse` being `nil` means we don't know yet if we can write without response or with response. As soon as we figure it out we set it and use that from that point on (so we don't have to check every time). This is an improvement over Bluejay 👍

2022-09-15 12:51 UTC, DantePuglisi commented on Sources/BleTransport/Module/BleModule.swift
> +    func start(delegate: BleModuleDelegate) {
That was my idea originally of course but I need to pass `self` in the `CBCentralManager` constructor which can't be done before `super.init` (if built in an `init`) and `delegate` and `cbCentralManager` parameters can't be set after `super.init`

2022-09-15 19:08 UTC, DantePuglisi commented
Actioned all Code Review items 👍

2022-09-19 09:57 UTC, harrisonf-ledger commented
I was able to test this with Connect and noticed that if a device isn't already paired to my phone, it won't automatically request to pair. Is that intentional? It would be great if we could preserve that behavior.

2022-09-22 05:22 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/BleModule.swift
> +        operationsQueue.operationsOfType(Connect.self).first?.didDisconnectPeripheral()
We should pass the error to `didDisconnectPeripheral` to avoid the less specific `unexpectedDisconnect` error.

2022-09-22 06:10 UTC, harrisonf-ledger commented on Sources/BleTransport/Module/Connect/Connect.swift
> +        guard let cbPeripheral = manager.retrievePeripherals(withIdentifiers: [peripheralIdentifier.uuid]).first else { complete(.failure(ConnectionError.unexpectedDisconnect)); return }
Can we throw a more detailed error here?

2022-10-03 12:03 UTC, harrisonf-ledger approved these changes

2022-10-03 13:29 UTC, merged